spring:
  application:
    name: product-service

resilience4j:
  circuitbreaker:
    instances:
      productServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      products:
        maxAttempts: 3 
        waitDuration: 200ms
        
server:
  port: 9090
